import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Co-Founders | Tab Startup ",
  description: "Generated by create next app",
};

const CoFoundersPage = () => {
  return <div></div>;
};

export default CoFoundersPage;
