import WhyJoinTab from "@/components/About/WhyJoinTab";

import ContactUs from "@/components/ContactUs/ContactUs";
import BusinessPlan from "@/components/Home/BusinessPlan";
import ConncetUs from "@/components/Home/ConncetUs";
import FAQ from "@/components/Home/FAQ";
import HeroBanner from "@/components/Home/HeroSection/HeroBanner";
import Services from "@/components/Home/Services";
import WhyTabStartup from "@/components/Home/WhyTabStartup";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Home | Tab Startup ",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <>
      <HeroBanner />
      <Services />
      <BusinessPlan />
      <WhyTabStartup />
      <WhyJoinTab />
      <ConncetUs />
      <FAQ />
      <ContactUs />
    </>
  );
};

export default HomePage;
