import SectionBanner from "@/components/ui/SectionBanner";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About | Tab Startup ",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <SectionBanner
        backgroundImagePath="/assets/background/blue-gradiant.png"
        className="text-white"
        title="About Tab Startup"
      />
    </div>
  );
};

export default AboutPage;
