import ContactUs from "@/components/ContactUs/ContactUs";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Contact | Tab Startup ",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <>
      <ContactUs />
    </>
  );
};

export default ContactPage;
