import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tab Startup",
  description: "Generated by create next app",
};

export type ChildrenType = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: ChildrenType) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className="bg-slate-200">{children}</body>
    </html>
  );
};

export default RootLayout;
